# Generated by Django 4.1.7 on 2023-04-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar'), ('UKG', 'Hrivna')], default='USD', max_length=3),
        ),
    ]
